### ISSUE TITLE
Confirmation on delete

### ISSUE THREAD

**Issue by flauc** [Jaspero/bpmn#5]
![image](https://github.com/Jaspero/bpmn/assets/4489834/747a8af7-9bf2-4360-8e0c-39542e08abd7)

When hitting delete we need to first ask for confirmation. This should use our web component confirmation.

**Comment by KovaCro** [comment]
@flauc Should there be confirmation when deleting versions as well?

**Comment by flauc** [comment]
Sure let's do it
